[build-system]
requires = ["setuptools>=68.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "concert-scribe"
version = "0.1.6"
description = "Classify audio segments in concert recordings"
requires-python = ">=3.9"
dependencies = [
    "tensorflow>=2.13",
    "tensorflow-hub>=0.14",
    "numpy>=1.23",
    "setuptools",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
    "twine",
]

[project.scripts]
concert-scribe = "concert_scribe.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
